//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizzify.Quester.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quizzify.Quester.Resources.Locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add question.
        /// </summary>
        public static string AddNewQuestionButtonResources {
            get {
                return ResourceManager.GetString("AddNewQuestionButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add round.
        /// </summary>
        public static string AddNewRoundButtonResources {
            get {
                return ResourceManager.GetString("AddNewRoundButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add theme.
        /// </summary>
        public static string AddNewThemeButtonResources {
            get {
                return ResourceManager.GetString("AddNewThemeButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Answer.
        /// </summary>
        public static string AnswerTextBlockResources {
            get {
                return ResourceManager.GetString("AnswerTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New file.
        /// </summary>
        public static string CreateNewFileButtonResources {
            get {
                return ResourceManager.GetString("CreateNewFileButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DeleteButtonResources {
            get {
                return ResourceManager.GetString("DeleteButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Difficulty:.
        /// </summary>
        public static string DifficultyTextBlockResources {
            get {
                return ResourceManager.GetString("DifficultyTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LanguageTextBlockResources {
            get {
                return ResourceManager.GetString("LanguageTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string OpenFileButtonResources {
            get {
                return ResourceManager.GetString("OpenFileButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Package name:.
        /// </summary>
        public static string PackageNameTextBlockResources {
            get {
                return ResourceManager.GetString("PackageNameTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string QuestionPriceTextBlockResources {
            get {
                return ResourceManager.GetString("QuestionPriceTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question.
        /// </summary>
        public static string QuestionTextBlockResources {
            get {
                return ResourceManager.GetString("QuestionTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round name:.
        /// </summary>
        public static string RoundNameTextBlockResources {
            get {
                return ResourceManager.GetString("RoundNameTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round.
        /// </summary>
        public static string RoundTextBlockResources {
            get {
                return ResourceManager.GetString("RoundTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string SaveFileButtonResources {
            get {
                return ResourceManager.GetString("SaveFileButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsTextBlockResources {
            get {
                return ResourceManager.GetString("SettingsTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share.
        /// </summary>
        public static string ShareFileButtonResources {
            get {
                return ResourceManager.GetString("ShareFileButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag:.
        /// </summary>
        public static string TagTextBlockResources {
            get {
                return ResourceManager.GetString("TagTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme name:.
        /// </summary>
        public static string ThemeNameTextBlockResources {
            get {
                return ResourceManager.GetString("ThemeNameTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string ThemeTextBlockResources {
            get {
                return ResourceManager.GetString("ThemeTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string TypeQuestionTextBlockResources {
            get {
                return ResourceManager.GetString("TypeQuestionTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round type:.
        /// </summary>
        public static string TypeRoundTextBlockResources {
            get {
                return ResourceManager.GetString("TypeRoundTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mediafile.
        /// </summary>
        public static string UploadMediaButtonResources {
            get {
                return ResourceManager.GetString("UploadMediaButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add media:.
        /// </summary>
        public static string UploadMediaTextBlockResources {
            get {
                return ResourceManager.GetString("UploadMediaTextBlockResources", resourceCulture);
            }
        }
    }
}
