CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE TABLE "Packages" (
        package_id integer GENERATED BY DEFAULT AS IDENTITY,
        package_name character varying(50) NOT NULL,
        created_at date DEFAULT (CURRENT_DATE),
        difficulty integer NOT NULL,
        CONSTRAINT packages_pkey PRIMARY KEY (package_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE TABLE "SecretQuestions" (
        secret_q_id integer GENERATED BY DEFAULT AS IDENTITY,
        question_text text NOT NULL,
        CONSTRAINT secretquestions_pkey PRIMARY KEY (secret_q_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE TABLE "Rounds" (
        round_id integer GENERATED BY DEFAULT AS IDENTITY,
        package_id integer NOT NULL,
        name character varying(255) NOT NULL,
        round_type character varying(7) NOT NULL,
        CONSTRAINT rounds_pkey PRIMARY KEY (round_id),
        CONSTRAINT rounds_package_id_fk FOREIGN KEY (package_id) REFERENCES "Packages" (package_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE TABLE "Users" (
        user_id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        login character varying(20) NOT NULL,
        password_hash character varying(256) NOT NULL,
        email character varying(50) NOT NULL,
        selected_secret_question_id integer,
        secret_answer_hash character varying(256) NOT NULL,
        twofa_auth_method text,
        google_authorization bytea,
        CONSTRAINT users_pkey PRIMARY KEY (user_id),
        CONSTRAINT secret_question_fk FOREIGN KEY (selected_secret_question_id) REFERENCES "SecretQuestions" (secret_q_id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE TABLE "Questions" (
        question_id integer GENERATED BY DEFAULT AS IDENTITY,
        round_id integer NOT NULL,
        question_text text,
        question_theme character varying(15),
        question_image_url bytea,
        question_cost integer NOT NULL,
        question_comment text,
        answer_text text,
        answer_image_url bytea,
        CONSTRAINT questions_pkey PRIMARY KEY (question_id),
        CONSTRAINT questions_round_id_fk FOREIGN KEY (round_id) REFERENCES "Rounds" (round_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE TABLE "Players" (
        player_id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid NOT NULL,
        nickname character varying(20) NOT NULL,
        user_profile_picture bytea,
        about text,
        CONSTRAINT players_pkey PRIMARY KEY (player_id),
        CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES "Users" (user_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE UNIQUE INDEX players_user_id_key ON "Players" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE INDEX "IX_Questions_round_id" ON "Questions" (round_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE INDEX "IX_Rounds_package_id" ON "Rounds" (package_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE INDEX "IX_Users_selected_secret_question_id" ON "Users" (selected_secret_question_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE UNIQUE INDEX users_email_key ON "Users" (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    CREATE UNIQUE INDEX users_login_key ON "Users" (login);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240327191229_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240327191229_InitialCreate', '8.0.2');
    END IF;
END $EF$;
COMMIT;

