//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizzify.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quizzify.Resources.Locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string AuthorizationButtonResources {
            get {
                return ResourceManager.GetString("AuthorizationButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string EmailTextBlockRersources {
            get {
                return ResourceManager.GetString("EmailTextBlockRersources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Login.
        /// </summary>
        public static string EnterAccountTextBlockResources {
            get {
                return ResourceManager.GetString("EnterAccountTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Existing Account?.
        /// </summary>
        public static string ExistingAccountTextBlockResources {
            get {
                return ResourceManager.GetString("ExistingAccountTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help Me.
        /// </summary>
        public static string HelpMeTextBlockResources {
            get {
                return ResourceManager.GetString("HelpMeTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You will be automatically logged in the app starts until you log in from somewhere else..
        /// </summary>
        public static string HintToolTipToggleButtonResources {
            get {
                return ResourceManager.GetString("HintToolTipToggleButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LanguageTextBlockResources {
            get {
                return ResourceManager.GetString("LanguageTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LoginTextBlockResources {
            get {
                return ResourceManager.GetString("LoginTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Account?.
        /// </summary>
        public static string NoAccountTextBlockResources {
            get {
                return ResourceManager.GetString("NoAccountTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string PasswordTextBlockResources {
            get {
                return ResourceManager.GetString("PasswordTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Account.
        /// </summary>
        public static string RegisterOnTextBlockResources {
            get {
                return ResourceManager.GetString("RegisterOnTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string RegistrationButtonResources {
            get {
                return ResourceManager.GetString("RegistrationButtonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsTextBlockResources {
            get {
                return ResourceManager.GetString("SettingsTextBlockResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep me logged in.
        /// </summary>
        public static string StayOnlineTextBlockResources {
            get {
                return ResourceManager.GetString("StayOnlineTextBlockResources", resourceCulture);
            }
        }
    }
}
